apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "FTP-RULE"
specs:
  - description: "For endpoints with env=prod, only allow if source also has label env=prod"
    endpointSelector:
      matchLabels:
        env: prod  
       
    ingress:
    - fromRequires:
      - matchLabels:
          env: prod
      